# Generated by Django 3.2.8 on 2021-11-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
